# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Traject
title-normal: purposful & delightful forms
email: hello@traject.nz
description: purposeful, delightful forms for government agencies
baseurl:  # the subpath of your site, e.g. /blog
url: "localhost" # the base hostname & protocol for your site
author:
street_address: 1/7 Dixon Street
city: Te Aro
state: Wellington
zip_code: 6011
country: New Zealand
phone: 022-192-8504

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/trajectnz
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/traject-new-zealand
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Traject_NZ

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: trajectnz
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
